### ISSUE TITLE
Missing Back-end

### ISSUE THREAD

**Issue by kmacod** [chronikum/FUSC#1]
I have a few ideas

1. Build a WebApp using Python and DJango.
2. Use Postgresql for the database.
3. Perform automated backup for the database so we don't lose any data.

Benefits
1. Python makes it easy for web scraping and it runs on all platform. This can be used to obtain a dataset from various sites, such as http://www.fakenamegenerator.com/ which we can use to fill in the forms.

I am assuming that the browser extension or the mobile apps that fill in the forms will only obtain data from the server using an API.

We should also make it so whenever someone set up a FUSC server, it automatically obtains a list of other servers that are online.

The question is what differenciates this service as an anti-phising service but not just another fake identity/fake information form filler?

**Comment by chronikum** [comment]
I really like that idea!
I think python is a good choice, sadly I don't have really experience in working with it.

Of course it is possible to use as browser extension, but I think we could do that also "full-automated".
As example:

The program runs in the background and if you don't need your pc (or server) it uses it resources to fill up formulas which were submitted and approved by and off the community.
(The more formulas you fill, the more weight your voice has in voting about submitted scam sites)

A FUSC-Server is a good idea, I would definitely be willing to rent a server if needed!
